from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

# Initialize SQLAlchemy
db = SQLAlchemy()

class Batch(db.Model):
    """
    Represents a group/batch of seaweed samples being tracked.
    Each batch can contain multiple Quality Control (QC) records.
    """
    __tablename__ = 'batches'
    
    # Primary Key
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # Unique identifier/code for the batch (e.g., 'batch_01_2026')
    code = db.Column(db.String(50), unique=True, nullable=False)
    
    # Human-readable name for the batch
    name = db.Column(db.String(100), nullable=False)
    
    # Date when the batch was registered/started (ISO format)
    batch_date = db.Column(db.String(20), nullable=False)
    
    # One-to-Many Relationship: A Batch has many QCRecords. 
    # cascade="all, delete-orphan" ensures records are deleted if the batch is removed.
    qc_records = db.relationship('QCRecord', backref='batch', lazy=True, cascade="all, delete-orphan")

    def to_dict(self):
        """Converts the Batch instance into a dictionary for JSON responses."""
        return {
            'id': self.id,
            'batchCode': self.code,
            'batchName': self.name,
            'batchDate': self.batch_date
        }

class QCRecord(db.Model):
    """
    Represents a single Quality Control analysis record for a specific batch.
    Stores biological data, scoring, and analysis metadata.
    """
    __tablename__ = 'qc_records'
    
    # Primary Key
    id = db.Column(db.Integer, primary_key=True)
    
    # Foreign Key linking back to the Batch
    batch_id = db.Column(db.Integer, db.ForeignKey('batches.id'), nullable=False)
    
    # Date and time of the analysis (ISO format)
    date = db.Column(db.String(20), nullable=False)
    
    # Name of the technician who performed the analysis
    technician = db.Column(db.String(100), nullable=False)
    
    # Whether contamination was observed ('Yes' or 'No')
    contamination = db.Column(db.String(10), nullable=False)
    
    # Type of contaminant (e.g., 'bacteria', 'fungi') if contamination is 'Yes'
    contaminant = db.Column(db.String(100), nullable=True)
    
    # Numeric quality score given during analysis (0-10)
    quality_scoring = db.Column(db.Integer, nullable=False)
    
    # Current developmental stage of the seaweed
    developmental_stage = db.Column(db.String(100), nullable=False)
    
    # Ratio of male and female gametophytes in the sample
    biological_sex_ratio = db.Column(db.String(50), nullable=True)
    
    # Optional notes/comments from the analyst or generated by AI
    comment = db.Column(db.String(500), nullable=True)
    
    # URL to the analyzed image or video stored on the server
    image_url = db.Column(db.String(500), nullable=True)

    def to_dict(self):
        """Converts the QCRecord instance into a dictionary for JSON responses."""
        return {
            'id': self.id,
            'date': self.date,
            'technician': self.technician,
            'contamination': self.contamination,
            'contaminant': self.contaminant,
            'qualityScoring': self.quality_scoring,
            'developmentalStage': self.developmental_stage,
            'biologicalSexRatio': self.biological_sex_ratio,
            'comment': self.comment,
            'imageUrl': self.image_url
        }
